community-local-playbook.yml, community/docs/modules/ROOT/nav.adoc, enterprise-local-playbook.yml, enterprise/docs/modules/ROOT/nav.adoc, generate-nav.py
The script was checking for '/' to count the depth of pages, windows uses '\\' hence the depth always was 0. Now it should be agnostic by using os.path.sep.
Added a IS_WINDOWS flag to replace '\\' with '/' as the os.path.join function will use '\\' to form windows paths. Simplest solution was to replace '\\' with '/' before writing to the file. Forward slashes are necessary for the nav.adoc as that is what is used when the URL is served, using '\\' in the URL will cause them to be malformed and navigation to break.
I also edited the local playbooks to use the local repository to build the documentation. This should allow netifly to show changes in the pull request.
=> Navigation Script Windows Bug Fixes

community/docs/modules/ROOT/pages/Security/Security Fix List.adoc, enterprise/docs/modules/ROOT/pages/Security/Security Fix List.adoc
When CVE-2020-36518 was fixed there was no PR to document it in the fixes list. Documenting this CVE now.
**CVE:** https://nvd.nist.gov/vuln/detail/CVE-2020-36518
=> SERV-793 Document CVE-2020-36518 fix in Security Fixes

community/docs/antora.yml, community/docs/modules/ROOT/nav.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Notifiers/Custom Notifiers.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Project Management Tools/Gradle Plugin.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Project Management Tools/Maven Bom.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Project Management Tools/Maven Plugin.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Jakarta EE API/Enterprise Java Beans (EJB)/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/Phone Home.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Docker Host Support/Docker Nodes.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Domain Data Grid And Hazelcast/Datagrid in Applications.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Security Configuration/Client Certificates/Custom Validators.adoc, enterprise/docs/antora.yml, enterprise/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc
Antora provides the `page-version` attribute, which is a shortform alias for page-component-version. It will output the current version set in antora.yml, e.g. 5.2022.3 or 5.41.0, etc.
currentVersion is only updated during release, meaning it will match the version in antora.yml, meaning it is redundant and we can utilize the Antora attribute.
=> Remove the need to specify currentVersion

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Jakarta EE API/Enterprise Java Beans (EJB)/Overview.adoc
Reverts payara/Payara-Documentation#25
Reverted from release: https://github.com/payara/Payara-Enterprise/pull/618
=> Revert "FISH-5747 Add documentation about java.naming.factory.initial property"

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/JMX Monitoring.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Application Deployment/Deployment Descriptors.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/JVM Options.adoc
JVM Options page currently only documents JDK Versions for JVM Options (IMO not making it a JVM Options page, so I did some slight reordering of this page)
Miscellaneous JVM Options currently have no place to be documented (That I could find) so I added a section for documenting the various JVM Options.
=> SERV-40 Document JVM Settings for Encoding Config Files

community/docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc, enterprise/docs/modules/ROOT/nav.adoc
Documents the JDK 17 Considerations for Payara Embedded. Currently there is no documentation page dedicated to Payara Embedded so I had to document that too.
Put the page at the same level as the Payara Docker Images - If you feel there is a better place for it let me know
=> SERV-804 Document Payara Embedded & Its JDK 17 Considerations

community/docs/modules/ROOT/nav.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/Overview.adoc, enterprise/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/Overview.adoc
Add reference to versions which use open tracing 0.33.0.
Separated the Overview page into Community and Enterprise specific pages as they refer to different version ranges.
The large Nav changes are due to the script not being fully idempotent - the script updates in #37 will alleviate that.
=> Update Documentation with Reference to Opentracing 0.33.0

community/docs/modules/ROOT/nav.adoc, community/docs/modules/ROOT/partials/appendix.adoc, enterprise/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/partials/appendix.adoc, generate-nav.py
- Place Appendix into Partial file (To stop it being generated automatically - the only updates required now will be in the antora.yml)
- Utilize the antora.yml attributes (Less redundancy)
We initially introduced a rewrite rule with Apache, which has been broken since Phase-1, the overview has been using the antora.yml attributes which is less fragile and easier to update, this just standardizes it to all parts.
=> SERV-799 Fix dtd

community/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/nav.adoc, generate-nav.py
"ord" was being matched in every file path and hence skipped if true, mistake in trying to skip 'ord' files. Using regex fixes the issue.
=> Fix matching for 'ord' when creating xfiles

enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.40.0.adoc
=> SERV-840 Add FISH-5976 To Release Notes (5.40.0)

enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.40.0.adoc
=> SERV-840 Add FISH-5976 To Release Notes (5.41.0)

enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.40.0.adoc
=> SERV-840 Add FISH-5976 To Release Notes (5.42.0)

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/Password Aliases.adoc
As mentioned in https://github.com/payara/Payara/issues/5887 it's not documented anywhere that password aliases don't trim whitespace.
=> SERV-841 Document Password Aliases Not Trimming Whitespace

community/docs/modules/ROOT/pages/General Info/Getting Started.adoc, enterprise/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/pages/General Info/Getting Started.adoc, enterprise/docs/modules/ROOT/pages/General Info/Support Integration.adoc, enterprise/docs/modules/ROOT/pages/General Info/Supported Platforms.adoc
Minor fixes to the Getting Started page, and added missing page to the Enterprise component.
This PR has to be replicated in existing branches for `5.43.0` and `5.2022.3`
=> Fixes to getting started section and added missing page on Enterprise

community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc
Payara 6 docker images have JDK 11 as the default, not JDK 8. The rest of the page appears to be applicable still.
=> FISH-6574 Payara 6 Docker Changes

community/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Configuration and Management/Micro Management/Command Line Options/Command Line Options.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Configuration and Management/Micro Management/Configuring An Instance.adoc, enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.44.0.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc
Retroactively document the --noHazelcast and --noCluster options for Payara Micro & the docker image. Adds a breaking change notice (Reviewed by Dominika).
Docs will be republished for this change
=> FISH-372 (e5.44.0) Document Option to Disable Clustering Functionality of Hazelcast on Payara Micro

community/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Configuration and Management/Micro Management/Command Line Options/Command Line Options.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Configuration and Management/Micro Management/Configuring An Instance.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc
Documents the --noHazelcast and --noCluster options for Payara Micro & the docker image.
=> FISH-372 (P6) Document Option to Disable Clustering Functionality of Hazelcast on Payara Micro

community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Upgrade Payara/Backup and Restore Method.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Upgrade Payara/Domain and Node Directories Method.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Upgrade Payara/Overview.adoc
Changes references to Payara 5 -> Payara 6. No changes applied to Enterprise docs here as the version number is unknown and the upgrade methods will be different.
Removed JDK 11 and 17 upgrade considerations and all Payara 6 distributions available will contain everything for JDK 11 & 17
=> SERV-876 (P6) Update Considerations for Payara 6

community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
Cherry Pick https://github.com/payara/Payara-Documentation/pull/53 for Payara 6 documentation
=> FISH-6298 (P6) Yaml result added with the explanation about 'endpoints'

community/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc
Docker images now use JDK 11 as the base version, update the documentation to reflect this
=> FISH-6574 (P6) Docker Images JDK 11

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Security Configuration/Client Certificates/Custom Validators.adoc
FISH-5646: new version of Client Certificate validator doesn't have the Injection possibilities
=> FISH-5646: new version of Client Certificate validator doesn't have the Injection possibilities

docs/modules/ROOT/pages/Technical Documentation/Public API/Clustered Singleton.adoc
Documents the fix for the typo in the Clustered annotation: https://github.com/payara/Payara/pull/6024
Also includes another couple of typo fixes.
=> FISH-1175 Typo in Clustered Annotation

community/docs/modules/ROOT/pages/Security/Security Fix List.adoc, enterprise/docs/modules/ROOT/pages/Security/Security Fix List.adoc
Documents CVE-2022-42920 in the Security Fix List.
=> FISH-6715 (P6) CVE-2022-42920 Fix List Documentation

enterprise/docs/modules/ROOT/pages/Security/Security Fix List.adoc
Adds security fix list information for CVE-2022-1292 CVE-2022-2068 fixed in https://github.com/payara/Payara-Enterprise/pull/731
=> FISH-6644 (Ent-Docs) Security Fix List

community/docs/modules/ROOT/pages/Security/Security Fix List.adoc
Adds security fix list information for CVE-2022-1292 CVE-2022-2068 fixed in https://github.com/payara/Payara/pull/6104
=> FISH-6644 (P6-Docs) Security Fix List

community/docs/modules/ROOT/pages/Release Notes/Release Notes 5.2022.4.adoc, community/docs/modules/ROOT/pages/Release Notes/Release Notes 5.2022.5.adoc, community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc, enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.46.0.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
Based on the findings of FISH-6927, adapted the documentation of the MP OpenAPI configuration properties to list `mp.openapi.scan.lib` as an extension property.
The following PRs were made to port this one to its contemporary branch releases:
* #174 
* #175
* #176
* #177
=> Edited MP OpenAPI extension properties

community/docs/modules/ROOT/pages/Release Notes/Release Notes 6.2022.2.adoc
Missed this detail in the last release.
=> Added missing credits for FISH-6775 reporters

community/docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Overview.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/SSO Integration.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Versioning.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Apache Kafka.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Azure SB.adoc, docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/MQTT.adoc
Fixes formatting, broken links and missing anchors for Cloud Connector documentation. Also documents alternative versions of the cloud connectors and what their key differences are
=> FISH-6609 Update Cloud Connectors for JakartaEE 10

community/docs/modules/ROOT/pages/Security/Security Fix List.adoc, enterprise/docs/modules/ROOT/pages/Security/Security Fix List.adoc
As discussed in FISH-6845, after reviewing the details on CVE-2022-1471, added an advisory to clarify that this vulnerability doesn't affect the Payara Platform at all.
=> Added advisory for CVE-2022-1471

community/docs/antora.yml, docs/antora.yml
As there are no more releases of Payara 5 Community, it makes sense to have Payara 6 now be the default for the documentation.
=> Remove Prerelease

community/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/nav.adoc
The Payara 6 documentation had changes where the nav file wasn't updated
=> Payara6 Update Nav

enterprise/docs/modules/ROOT/partials/release-notes.adoc
5.49.0 Release Notes are missing from the partial page and therefore the nav bar. This has already been fixed in e5.49.0, this is the fix for master.
=> (Master) 5.49.0 Release Notes to Nav

community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
Fix `mp.openapi.extensions.scan.lib` property name
Update scanning of jars in ear's `lib/` directory, change introduced in FISH-6980
Merge after finishing Community change: https://github.com/payara/Payara-Documentation/pull/238
=> Fish 6980 add ear libs to openapi scan ent

enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Upgrade Payara/Upgrade Tool.adoc
Add caveat informing users to use 2.x releases of the upgrade tool for Payara 6
=> Upgrade Tool Caveat (Payara6)

enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc
Updates the default JVM_ARGS for the Payara Micro Docker image as per https://github.com/payara/Payara-Enterprise/pull/933
=> FISH-7740 Document Updated Default JVM_ARGS for Payara Micro Docker Image

community/docs/modules/ROOT/nav.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Certificate Management/Overview.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/SSL Certificates.adoc
Certificate Management has finally made the transition to being the extension it always was and should be documented as such.
https://github.com/payara/Payara/pull/6388
=> FISH-7721 Document Certificate Management as an Extension

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Classloading/Enhanced Classloading.adoc
Adds a comment that you cannot use a bundled JSF implementation as an EAR library.
Related PRs:
* https://github.com/payara/Payara/pull/6425
* https://github.com/payara/Payara-Enterprise/pull/966
=> FISH-6519 Add useBundledJsf EAR Comment

docs/modules/ROOT/pages/Technical Documentation/Public API/Overview.adoc
Updates the Payara-API documentation with the new versioning info that came about from the Core vs. Server split internally.
=> FISH-8083 Update Payara-API Documentation

community/docs/modules/ROOT/pages/Security/Security Fix List.adoc, enterprise/docs/modules/ROOT/pages/Security/Security Fix List.adoc
Adding list of cve's fixed by okhttp upgrade
=> FISH-7833: adding list of fixed cve's by upgrading okhttp

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/collect-log-files.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/create-service.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/export-sync-bundle.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/import-sync-bundle.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/install-node-dcom.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/install-node-ssh.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/install-node.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/list-nodes-config.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/list-nodes-dcom.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/list-nodes-ssh.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/start-instance.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/start-local-instance.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-dcom.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-ssh.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/update-node-config.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/update-node-dcom.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/domains.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/rest-interface.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/High Availability/ssh-setup.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Asadmin Commands/Server Management Asadmin Commands.adoc, stashed_docs/modules/performance-tuning-guide/pages/preface.adoc
Fixed several references to `glassfish3` in sample file paths across the revamped documentation.
=> Fixed glassfish3 path references

community/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Payara Micro Docker Image.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Docker Image.adoc
Adds a small note about us providing AMD64 and ARM64 images, and that Docker should sort it out for them
=> FISH-7821 FISH-8190 Add Docker ARM64 Note

enterprise/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.14.0/Overview.adoc, enterprise/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.14.0/Server TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.14.0/Server Web TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Jakarta EE Certification/6.14.0/6.14.0 (Web Profile) Core TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Jakarta EE Certification/6.14.0/6.14.0 (Web Profile) Web TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Jakarta EE Certification/6.14.0/6.14.0 Core TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Jakarta EE Certification/6.14.0/6.14.0 Platform TCK Results.adoc, enterprise/docs/modules/ROOT/pages/Release Notes/Overview.adoc, enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 6.14.0.adoc, enterprise/docs/modules/ROOT/partials/eclipse-microprofile.adoc, enterprise/docs/modules/ROOT/partials/jakarta-ee.adoc, enterprise/docs/modules/ROOT/partials/release-notes.adoc
FISH-8603 Payara Enterprise 6.14.0 Release Notes and TCK Results
Removing Opentracing as its no longer  part of MP 6.1 https://microprofile.io/compatible/6-1/#overview
=> FISH-8603 Payara Enterprise 6.14.0 Release Notes and TCK Results

enterprise/docs/modules/ROOT/nav.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/collect-diagnostics.adoc, enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Diagnostics and Troubleshooting/Diagnostics Tool.adoc
The counterpart of #435 for the Payara Platform 6.
Documentation of the latest diagnostic tool introduced for Payara Enterprise. Also documented the new command in the server's command reference.
=> [FISH-8387] - Diagnostics tool documentation

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/General Runtime Administration.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc
Documented the system properties implemented in https://github.com/payara/Payara/pull/6318.
These properties have introduced custom behaviour to the Data Grid / Hazelcast and were missing from the current documentation.
This documentation has to be applied retroactively from release `6.9.0`
=>  [FISH-7640] Custom Hazelcast System Properties

docs/modules/ROOT/pages/Technical Documentation/Application Development/Debugging Applications.adoc
Re-documented instructions on setting up correct classloading debugging for Payara Server since JDK 9+ no longer supports the `-verbose` option.
=> Fixed class loading debugging information.

docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Versioning.adoc
Minor fixes related to the versions of the SQS connector and updated installation instructions, encouraging users to download the SQS connectors via Maven Central rather than building from the source.
=> [Payara 6 Documentation] Updated version numbers and installation instructions for Amazon SQS connectors

docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Versioning.adoc
Minor fixes related to the versions of the SQS connector and updated installation instructions, encouraging users to download the SQS connectors via Maven Central rather than building from source.
=> [Payara 5 Documentation] Updated version numbers and installation instructions for Amazon SQS connectors

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
Fix incorrect Asadmin CLI sample for enabling/disabling an HTTP network listener
=> Fix incorrect HTTP listener attribute name

community/docs/antora.yml, enterprise/docs/antora.yml
Fixed links for the DTD schemas of the `payara-web.xml` and `payara-resources.xml` deployment descriptors.
=> Fixes to Payara DD DTD file links

community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Notifiers/SNMP.adoc
- Updates the version numbers used in the Community documentation for the SNMP notifier from 3.7.5 to 3.8.2.
- Updates the URL to what is likely to be the URL for the next repackaged SNMP4J release.
=> FISH-10016 Update SNMP Library Versions in Notifier documentation

community/docs/antora.yml, docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_8.dtd, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Application Deployment/Elements of Deployment Descriptors.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/create-javamail-resource.adoc, enterprise/docs/antora.yml
Adds 1_8 dtd to documentation and changes the `com.sun.mail` package references to `org.eclipse.angus.mail`.
=> FISH-9777 AngusMail

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
this is documentation for new properties added on the grizzly implementation to protect against RFC-9110 invalid characters on the Http Header Name and Http Header Validation
=> FISH-9690: adding documentation for new grizzly properties to protect from RFC-9110 invalid characters

community-local-playbook.yml, enterprise-local-playbook.yml
Bumped the version of the Antora theme used to build the HTML site to the newly published `v2.0` release.
=> Updated local playbooks to use v2.0 Antora custom theme.

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/create-managed-executor-service.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/create-managed-scheduled-executor-service.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/create-managed-thread-factory.adoc
Describing configuration of virtual threads in MES, MSES, MFT.
Also remove obvious copy&paste error, `taskqueuecapacity` in MSES.
=> FISH-8302 Describe Configuration of Virtual Threads in Concurrency Resources

docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Overview.adoc
This adds a paragraph mentioning that Payara Arquillian connectors work with Arquillian-junit5, with a link to an example using junit5 (the link will work only after the new subproject is merged, see https://github.com/payara/Payara-Examples/pull/205)
=> FISH-10828 - mention junit5 with arquillian connector for P7

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc
I have updated the documentation to reflect on the warlib changes. 
I have added that `--warlibs` takes precedence over `--properties warlibs` .
=> FISH-11138 - updated deploy documentation

docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/deploy-remote-archive.adoc, docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Command Reference/redeploy.adoc
Adds missing warlibs documentation to the redeploy and deploy-remote-archive commands.
=> FISH-12093 FISH-12132 Add More Missing Warlibs Documentation
